name: orator_teleprompter
description: "Professional Teleprompter App for creators."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos estándar
  cupertino_icons: ^1.0.8
  
  # BASE DE DATOS: Conexión con Supabase
  supabase_flutter: ^2.8.0

  # DISEÑO Y MULTIMEDIA
  google_fonts: ^6.2.1
  image_picker: ^1.2.1
  
  # --- INFRAESTRUCTURA DE VIDEO Y CÁMARA ---
  camera: ^0.11.0             # Control de la cámara HD
  video_player: ^2.8.1        # Para reproducir tus grabaciones
  video_thumbnail: ^0.5.3     # Genera las fotos de la galería
  path_provider: ^2.1.1       # Gestión de archivos locales (.mp4)

  # --- SEGURIDAD Y MONETIZACIÓN ---
  google_mobile_ads: ^5.1.0    # Gana dinero con anuncios antes de descargar
  screen_protector: ^1.0.1     # ¡ESCUDO! Evita que graben pantalla sin pagar
  gal: ^2.1.3                  # Guarda el video final en el carrete del usuario
  permission_handler: ^11.3.1  # Permisos de cámara, micro y galería

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"