default_platform(:ios)

platform :ios do
  desc "Despliegue a la App Store"
  lane :release do
    # Crea la API Key desde las variables de entorno que pasamos en el YML
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      is_key_content_base64: false,
      duration: 1200,
      in_house: false
    )

    # Construye la app (asegúrate de que el esquema sea correcto)
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    # Sube a TestFlight
    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end